[features]
seeds = false
skip-lint = false
[programs.localnet]
d21 = "5XNUoAV88Ahuir9WWYdFH3T546qGbEiPG4p1LNhSe7Mg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/reastyn/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
